
# 1. Install dependencies
echo "Installing dependencies from requirements.txt..."
pip install -r requirements.txt

# 2. Print instructions
echo ""
echo "========================================="
echo "Project Run Instructions"
echo "========================================="
echo "You need 3 terminals to run this project:"
echo ""
echo "---"
echo "Terminal 1: HF Manager Agent"
echo "---"
echo "1. Run the HF Manager Agent:"
echo "   python3 hf_agent.py"
echo "2. Copy the agent address that is printed (e.g., agent1q...)."
echo ""
echo "---"
echo "Terminal 2: Orchestrator Agent"
echo "---"
echo "1. Open orchestrator_agent.py in your editor."
echo "2. Paste the HF Manager's address into the 'hf_manager_address' variable."
echo "3. Run the Orchestrator Agent:"
echo "   python3.12 orchestrator_agent.py"
echo ""
echo "---"
echo "Terminal 3: Client Agent (Choose one path)"
echo "---"
echo "You can now test any of the following paths:"
echo ""
echo "  Path 1: Test Transient Model (Directly)"
echo "  - Edit 'simple_agent_to_send_message_hf_transient.py' to set the HF agent address."
echo "  - Run: python3 simple_agent_to_send_message_hf_transient.py"
echo ""
echo "  Path 2: Test Persistent Model (Directly)"
echo "  - Edit 'simple_agent_to_send_message_hf_persistent.py' to set the HF agent address."
echo "  - Run: python3 simple_agent_to_send_message_hf_persistent.py"
echo ""
echo "  Path 3: Test Orchestrator (Knowledge Graph)"
echo "  - Edit 'simple_agent_to_send_message_orc_agent.py' to set the ORC agent address."
echo "  - Run: python3 simple_agent_to_send_message_orc_agent.py"
echo ""
echo "  Path 4: Test Orchestrator (Auto-Deployment)"
echo "  - Set THRESHOLD_TO_DEPLOY_NEW_AGENT = 2 in the orchestrator_agent.py config."
echo "  - Run the command from Path 3 twice."
echo "  - This will trigger the deployment of a new agent."
echo ""
echo "========================================="